on:
  pull_request:
  workflow_call:

name: Build and Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install
        run: npm install
      - name: build
        run: make build
      - name: test
        run: make test
